export {default as About} from "./About";
export {default as Contact} from "./Contact";
export {default as Footer} from "./Footer";
export {default as Home} from "./Home";
export {default as Nav} from "./Nav";
export {default as Portfolio} from "./Portfolio";
export {default as Resume} from "./Resume";
export {default as WhatIDo} from "./WhatIDo";
export {default as ScrollToTop} from "./ScrollToTop";
